# /// script
# requires-python = ">=3.11"
# ///
"""Generate all rose-pine-geist theme targets from palette.toml.

Usage: uv run build.py
Stdlib only (tomllib requires Python 3.11+, hence the uv pin above).
"""

import tomllib
from pathlib import Path

ROOT = Path(__file__).parent

HEADER = "Generated by `uv run build.py` from palette.toml. Do not edit by hand."


def build_nvim(p: dict[str, str]) -> str:
    # Keys mirror rose-pine/neovim's lua/rose-pine/palette.lua (main variant).
    order = [
        ("_nc", p["nc"]),
        ("base", p["base"]),
        ("surface", p["surface"]),
        ("overlay", p["overlay"]),
        ("muted", p["muted"]),
        ("subtle", p["subtle"]),
        ("text", p["text"]),
        ("love", p["love"]),
        ("gold", p["gold"]),
        ("rose", p["rose"]),
        ("pine", p["pine"]),
        ("foam", p["foam"]),
        ("iris", p["iris"]),
        ("leaf", p["leaf"]),
        ("highlight_low", p["highlight_low"]),
        ("highlight_med", p["highlight_med"]),
        ("highlight_high", p["highlight_high"]),
    ]
    lines = [f"-- {HEADER}", "return {"]
    lines += [f'\t{k} = "{v}",' for k, v in order]
    lines += ['\tnone = "NONE",', "}", ""]
    return "\n".join(lines)


def build_ghostty(p: dict[str, str]) -> str:
    # ANSI mapping mirrors the Rose Pine theme bundled with Ghostty,
    # except 0 (black) = surface so it stays distinct from the background.
    ansi = [
        p["surface"], p["love"], p["pine"], p["gold"],
        p["foam"], p["iris"], p["rose"], p["text"],
        p["muted"], p["love"], p["pine"], p["gold"],
        p["foam"], p["iris"], p["rose"], p["text"],
    ]
    lines = [f"# {HEADER}"]
    lines += [f"palette = {i}={c}" for i, c in enumerate(ansi)]
    lines += [
        f"background = {p['base']}",
        f"foreground = {p['text']}",
        # Accent-colored cursor, Vesper-style.
        f"cursor-color = {p['rose']}",
        f"cursor-text = {p['base']}",
        f"selection-background = {p['highlight_med']}",
        f"selection-foreground = {p['text']}",
        "",
    ]
    return "\n".join(lines)


# zsh-syntax-highlighting role map. Key parity with the previous
# catppuccin file; colors follow rose-pine semantics
# (commands=foam, keywords=pine, strings=gold, params/options=iris,
#  errors=love, comments=muted, punctuation=subtle).
ZSH_STYLES = [
    ("## Comments", None, None),
    ("comment", "muted", None),
    ("## Functions / commands", None, None),
    ("alias", "foam", None),
    ("suffix-alias", "foam", None),
    ("global-alias", "foam", None),
    ("function", "foam", None),
    ("command", "foam", None),
    ("precommand", "foam", "italic"),
    ("builtin", "foam", None),
    ("hashed-command", "foam", None),
    ("## Keywords", None, None),
    ("reserved-word", "pine", None),
    ("## Options / parameters", None, None),
    ("single-hyphen-option", "iris", None),
    ("double-hyphen-option", "iris", None),
    ("autodirectory", "gold", "italic"),
    ("## Punctuation / separators", None, None),
    ("commandseparator", "subtle", None),
    ("command-substitution-delimiter", "subtle", None),
    ("command-substitution-delimiter-unquoted", "subtle", None),
    ("process-substitution-delimiter", "subtle", None),
    ("back-quoted-argument-delimiter", "subtle", None),
    ("redirection", "subtle", None),
    ("## Escapes", None, None),
    ("back-double-quoted-argument", "pine", None),
    ("back-dollar-quoted-argument", "pine", None),
    ("back-quoted-argument", "iris", None),
    ("## Strings", None, None),
    ("command-substitution-quoted", "gold", None),
    ("command-substitution-delimiter-quoted", "gold", None),
    ("single-quoted-argument", "gold", None),
    ("single-quoted-argument-unclosed", "love", None),
    ("double-quoted-argument", "gold", None),
    ("double-quoted-argument-unclosed", "love", None),
    ("rc-quote", "gold", None),
    ("back-quoted-argument-unclosed", "love", None),
    ("## Variables", None, None),
    ("dollar-quoted-argument", "text", None),
    ("dollar-quoted-argument-unclosed", "love", None),
    ("dollar-double-quoted-argument", "iris", None),
    ("assign", "text", None),
    ("named-fd", "text", None),
    ("numeric-fd", "text", None),
    ("## Expansion", None, None),
    ("globbing", "iris", None),
    ("history-expansion", "iris", None),
    ("## Paths", None, None),
    ("path", "text", None),
    ("path_pathseparator", "subtle", None),
    ("path_prefix", "text", None),
    ("path_prefix_pathseparator", "subtle", None),
    ("## Fallback", None, None),
    ("unknown-token", "love", None),
    ("arg0", "text", None),
    ("default", "text", None),
    ("cursor", "text", None),
]


def build_zsh_highlighting(p: dict[str, str]) -> str:
    lines = [
        f"# {HEADER}",
        "# rose-pine-geist theme for zsh-syntax-highlighting.",
        "# Source this BEFORE zsh-syntax-highlighting itself.",
        "ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)",
        "typeset -gA ZSH_HIGHLIGHT_STYLES",
        "",
    ]
    for key, role, extra in ZSH_STYLES:
        if role is None:
            lines.append(key)
            continue
        style = f"fg={p[role]}" + (f",{extra}" if extra else "")
        lines.append(f"ZSH_HIGHLIGHT_STYLES[{key}]='{style}'")
    lines.append("")
    return "\n".join(lines)


def build_zsh_prompt(p: dict[str, str]) -> str:
    lines = [
        f"# {HEADER}",
        "# rose-pine-geist palette as shell variables, for prompts etc.",
    ]
    for k, v in p.items():
        lines.append(f'export RPG_{k.upper()}="{v}"')
    lines += [
        "",
        "# Example prompt:",
        '# PS1="%F{$RPG_FOAM}%n@%m%f:%F{$RPG_TEXT}%~%f %F{$RPG_ROSE}$ %f"',
        "",
    ]
    return "\n".join(lines)


def build_obsidian(p: dict[str, str]) -> str:
    # Obsidian exposes code-block colors as --code-* variables that both
    # the editor and reading view respect. The two selectors outrank
    # Minimal's scheme selector (.minimal-flexoki-dark.theme-dark) or tie
    # it and win by load order (snippets load after themes).
    roles = [
        ("normal", "text"),
        ("comment", "muted"),
        ("function", "rose"),
        ("important", "love"),
        ("keyword", "pine"),
        ("operator", "subtle"),
        ("property", "foam"),
        ("punctuation", "subtle"),
        ("string", "gold"),
        ("tag", "foam"),
        ("value", "rose"),
    ]
    # Scoped to code-BLOCK containers only (pre = reading view,
    # .HyperMD-codeblock = editor lines): CSS vars resolve from the nearest
    # ancestor, so fenced blocks get rose-pine colors while inline code and
    # backgrounds stay stock flexoki (warm), untouched by the snippet.
    lines = [
        f"/* {HEADER}",
        "   rose-pine-geist code-block colors for Obsidian (dark mode only).",
        "   Fenced blocks only — inline code stays stock. */",
        ".theme-dark pre,",
        ".theme-dark .HyperMD-codeblock {",
        # Alpha, not a palette hex: composites over the page color so the
        # recess inherits flexoki's warmth. 0.15 subtle .. 0.35 pronounced.
        "\t--code-background: rgba(0, 0, 0, 0.15);",
    ]
    lines += [f"\t--code-{name}: {p[role]};" for name, role in roles]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> None:
    with open(ROOT / "palette.toml", "rb") as f:
        palette = tomllib.load(f)["palette"]

    targets = {
        "nvim/lua/rose-pine-geist/palette.lua": build_nvim(palette),
        "ghostty/themes/rose-pine-geist": build_ghostty(palette),
        "zsh/rose-pine-geist-highlighting.zsh": build_zsh_highlighting(palette),
        "zsh/rose-pine-geist-prompt.zsh": build_zsh_prompt(palette),
        "obsidian/rose-pine-geist-code.css": build_obsidian(palette),
    }
    for rel, content in targets.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {rel}")


if __name__ == "__main__":
    main()
