# Generated by `uv run build.py` from palette.toml. Do not edit by hand.
# rose-pine-geist palette as shell variables, for prompts etc.
export RPG_NC="#000000"
export RPG_SURFACE="#000000"
export RPG_BASE="#0a0a0a"
export RPG_HIGHLIGHT_LOW="#1a1a1d"
export RPG_OVERLAY="#1f1f22"
export RPG_HIGHLIGHT_MED="#2e2e31"
export RPG_HIGHLIGHT_HIGH="#454548"
export RPG_MUTED="#6e6a86"
export RPG_SUBTLE="#908caa"
export RPG_TEXT="#e0def4"
export RPG_LOVE="#eb6f92"
export RPG_GOLD="#f6c177"
export RPG_ROSE="#ebbcba"
export RPG_PINE="#31748f"
export RPG_FOAM="#9ccfd8"
export RPG_IRIS="#c4a7e7"
export RPG_LEAF="#95b1ac"

# Example prompt:
# PS1="%F{$RPG_FOAM}%n@%m%f:%F{$RPG_TEXT}%~%f %F{$RPG_ROSE}$ %f"
