# Generated by `uv run build.py` from palette.toml. Do not edit by hand.
# rose-pine-geist colors for fzf.
export FZF_DEFAULT_OPTS="--color=fg:#908caa,bg:-1,hl:#eb6f92,fg+:#e0def4,bg+:#1a1a1d,hl+:#eb6f92,query:#e0def4,border:#31748f,prompt:#31748f,pointer:#eb6f92,marker:#ebbcba,spinner:#ebbcba,header:#6e6a86,info:#6e6a86,separator:#2e2e31,gutter:#31748f"
