# terminal
brew "fd"
brew "fzf"
brew "tree"
brew "tmux"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# pythons
brew "python@3.13"
brew "uv"

# javascripts
brew "fnm"
tap "oven-sh/bun"
brew "oven-sh/bun/bun"

# neovim
brew "luarocks"
brew "neovim"
brew "ripgrep"
brew "tree-sitter"
brew "tree-sitter-cli"

# devtools
brew "gh"
brew "git"
brew "git-lfs"
brew "gnupg"
cask "1password-cli"
cask "ungoogled-chromium"
cask "claude-code"
cask "codex"

tap "anomalyco/tap"
brew "anomalyco/tap/opencode"

brew "cmake"
brew "ffmpeg"
brew "gnutls"
brew "go"
brew "utf8proc"

brew "temporal"
